name: Landing Deploy
run-name: ${{ github.actor }} is deploying his new CV🔥🔥🔥
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Build Docker image
        run: |
          docker build -t landing:latest . -f backend/Dockerfile

      - name: Save Docker image
        run: |
          docker save landing:latest | gzip > landing.tar.gz

      - name: Copy files to server
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: "landing.tar.gz"
          target: "/home/${{ secrets.SSH_USER }}/landing/"

      - name: Deploy on server
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/${{ secrets.SSH_USER }}/landing/
            
            # Загружаем образ
            docker load < landing.tar.gz
            
            # Чистим старый тар
            rm landing.tar.gz
            
            # Перезапускаем через docker-compose
            docker compose down
            docker compose up -d

            # Убираем старые dangling-образы
            docker image prune -f
