name: Landing Deploy
run-name: ${{ github.actor }} is deploying his new CV🔥🔥🔥
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: List files
        run: ls -R

      - name: Build Docker image
        run: |
          docker build -t landing:latest ./backend

      - name: Save Docker image
        run: |
          docker save landing:latest | gzip > landing.tar.gz

      # 🧹 Очистка перед копированием
      - name: Clean remote directory
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            echo "Cleaning old files..."
            rm -rf /home/${{ secrets.SSH_USER }}/landing/frontend
            rm -f /home/${{ secrets.SSH_USER }}/landing/docker-compose.yml
            rm -rf /home/${{ secrets.SSH_USER }}/landing/backend

      # 📤 Копирование
      - name: Copy files to server
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: landing.tar.gz,docker-compose.yml,frontend,backend,images
          target: "/home/${{ secrets.SSH_USER }}/landing/"

      # 🚀 Деплой
      - name: Deploy on server
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/${{ secrets.SSH_USER }}/landing/
            
            # Загружаем образ
            docker load < landing.tar.gz
            
            # Чистим старый архив
            rm landing.tar.gz
            
            # Перезапускаем контейнеры
            docker compose down
            docker compose up -d --build

            # Чистим старые образы и volume'ы
            docker system prune -a -f --volumes
